---

- name: install {{ java_package }}
  become: yes
  yum:
    name: "{{ java_package }}"
    state: present

- name: set JAVA_HOME
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/java.sh"
    create: yes
    state: present
    regexp: '^export JAVA_HOME'
    line: "export JAVA_HOME=`java -XshowSettings:properties -version 2>&1 | sed '/^[[:space:]]*java\\.home/!d;s/^[[:space:]]*java\\.home[[:space:]]*=[[:space:]]*//'`"
