---

- name: install python2
  become: yes
  yum:
    name: "python2"
    state: present

- name: download {{ url }}
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ file }}"

- name: extract /tmp/{{ file }}
  become: yes
  become_method: sudo
  unarchive:
    src: "/tmp/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ cassandra_home }}"

- name: set ownership on {{ cassandra_home }}
  become: yes
  become_method: sudo
  file:
    path: "{{ cassandra_home }}"
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: 0755

- name: set PATH=$PATH:{{ cassandra_home }}/bin
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/cassandra.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ cassandra_home }}/bin'

- name: copy cassandra.yaml {{ cassandra_home }}/conf/cassandra.yaml
  template:
    src: templates/cassandra.yaml.j2
    dest: "{{ cassandra_home }}/conf/cassandra.yaml"
  register: cassandra_config

- name: create {{ cassandra_log_dir }}
  file:
    path: "{{ cassandra_log_dir }}"
    state: directory

- name: install cassandra systemd unit file
  become: yes
  become_method: sudo
  template:
    src: templates/cassandra.service.j2
    dest: "{{ system_units }}/cassandra.service"
  register: cassandra_service

- name: restart cassandra
  become: yes
  become_method: sudo
  when: cassandra_config.changed or cassandra_service.changed
  systemd:
    enabled: yes
    state: restarted
    name: cassandra
    daemon_reload: yes
