---
version: 3.0.2
spark: spark-{{ version }}-bin-without-hadoop #-scala-2.12
file: "{{ spark }}.tgz"
url: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/spark/spark-{{ version }}/{{ file }}
