---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "{{ download }}/{{ file }}"

- name: extract {{ download }}/{{ file }}
  become: yes
  become_method: sudo
  unarchive:
    src: "{{ download }}/{{ file }}"
    dest: "{{ usr_local }}"
    copy: no
    creates: "{{ flink_home }}"

- name: set ownership on {{ flink_home }}
  become: yes
  become_method: sudo
  file:
    path: "{{ flink_home }}"
    owner: vagrant
    group: vagrant
    recurse: yes
    mode: 0755

- name: set PATH=$PATH:{{ flink_home }}/bin
  become: yes
  become_method: sudo
  lineinfile:
    dest: "{{ etc_profiles }}/flink.sh"
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ flink_home }}/bin'

- name: install custom flink stop
  template:
    src: templates/stop-flink-yarn.sh.j2
    dest: "{{ flink_home }}/bin/stop-flink-yarn.sh"
    mode: 0755
  register: flink_stop

- name: install custom flink status
  template:
    src: templates/status-flink-yarn.sh.j2
    dest: "{{ flink_home }}/bin/status-flink-yarn.sh"
    mode: 0755

- name: install flink systemd unit file
  become: yes
  become_method: sudo
  template:
    src: templates/flink.service.j2
    dest: "{{ system_units }}/flink.service"
  register: flink_service

#- name: check if flink already started
#  become: yes
#  become_user: vagrant
#  shell: "{{ flink_home }}/bin/status-flink-yarn.sh"
#  ignore_errors: yes
#  register: flink_status

#- name: restart flink
#  become: yes
#  become_method: sudo
#  when: flink_service.changed or flink_stop.changed or flink_status.rc != 0
#  systemd:
#    enabled: yes
#    state: restarted
#    name: flink
#    daemon_reload: yes
