- hosts: all
  remote_user: vagrant
  serial: 100%
  roles:
  - java

- hosts: kafka
  remote_user: vagrant
  serial: 66%
  roles:
    - kafka

- hosts: cassandra
  remote_user: vagrant
  serial: 100%
  roles:
    - cassandra

- hosts: hadoop-master
  remote_user: vagrant
  serial: 100%
  roles:
    - hadoop

- hosts: hadoop-slave
  remote_user: vagrant
  serial: 100%
  roles:
    - hadoop

- hosts: hadoop-master
  remote_user: vagrant
  serial: 100%
  roles:
    - spark
    - flink
